### ISSUE TITLE
dockerclient does not compile anymore...

### ISSUE THREAD

**Issue by samalba** [samalba/dockerclient#132]
Looks like a regression introduced by #130 

```
$ go build
# dockerclient
./dockerclient.go:526: undefined: argAll
./dockerclient.go:528: undefined: argAll
```

**Comment by samalba** [comment]
Fixed by #131
