### PR TITLE
Fixed regression in ListImages() (fixes #132)

### LINKED ISSUE #132: dockerclient does not compile anymore...
Looks like a regression introduced by #130 

```
$ go build
# dockerclient
./dockerclient.go:526: undefined: argAll
./dockerclient.go:528: undefined: argAll
```

### PR DESCRIPTION
**Pull request by samalba**
Fixed regression

### CODE REVIEW

**Comment by samalba** [comment]
duplicate.
